#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <SOIL2/SOIL2.h>
#include <GL/glut.h>
#include "stack.h"
#include "vertex.h"
#include "draw.h"